package com.compomics.mslimsdatfileextractor;
        
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class DatFileExtractorDialog extends javax.swing.JDialog {

    /**
     * Dialog constructor.
     *
     * @param parent the parent dialog
     * @param modal is the dialog modal
     */
    public DatFileExtractorDialog(final Frame parent, final boolean modal) {
        super(parent, modal);

        initComponents();

        this.getContentPane().setBackground(Color.WHITE);
        this.getRootPane().setDefaultButton(runButton);
    }

    public JButton getCloseButton() {
        return closeButton;
    }

    public JPasswordField getDbPasswordTextField() {
        return dbPasswordTextField;
    }

    public JTextField getDbUrlTextField() {
        return dbUrlTextField;
    }

    public JTextField getDbUserNameTextField() {
        return dbUserNameTextField;
    }

    public JButton getRunButton() {
        return runButton;
    }

    public JTextField getProjectsTextField() {
        return projectsTextField;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbUserNameLabel = new javax.swing.JLabel();
        dbUserNameTextField = new javax.swing.JTextField();
        dbPasswordLabel = new javax.swing.JLabel();
        dbPasswordTextField = new javax.swing.JPasswordField();
        runButton = new javax.swing.JButton();
        dbUrlLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        dbUrlTextField = new javax.swing.JTextField();
        loginInfoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        projectsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("dat file extractor");

        dbUserNameLabel.setText("Database User Name");

        dbPasswordLabel.setText("Database Password");

        runButton.setText("run");
        runButton.setMaximumSize(new java.awt.Dimension(80, 25));
        runButton.setMinimumSize(new java.awt.Dimension(80, 25));
        runButton.setPreferredSize(new java.awt.Dimension(80, 25));

        dbUrlLabel.setText("Database Url");

        closeButton.setText("close");
        closeButton.setMaximumSize(new java.awt.Dimension(80, 25));
        closeButton.setMinimumSize(new java.awt.Dimension(80, 25));
        closeButton.setPreferredSize(new java.awt.Dimension(80, 25));

        loginInfoLabel.setText("Please provide the mslims database login credentials and project(s):");

        jLabel1.setText("Projects");

        projectsTextField.setToolTipText("The project numbers, comma separated.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbUrlLabel)
                            .addComponent(dbPasswordLabel)
                            .addComponent(dbUserNameLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbPasswordTextField)
                            .addComponent(dbUrlTextField)
                            .addComponent(dbUserNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(projectsTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUrlLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUserNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dbPasswordLabel;
    private javax.swing.JPasswordField dbPasswordTextField;
    private javax.swing.JLabel dbUrlLabel;
    private javax.swing.JTextField dbUrlTextField;
    private javax.swing.JLabel dbUserNameLabel;
    private javax.swing.JTextField dbUserNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginInfoLabel;
    private javax.swing.JTextField projectsTextField;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
